---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


Date format:
```{r}
Sys.setlocale("LC_TIME", 'en_US.UTF-8')
```

## Loading and preprocessing the data
```{r, loadingData, echo=TRUE, results="asis"}
require("knitr")
require('xtable')

dataDir <- "data"
if (!file.exists(dataDir)) {dir.create(dataDir)}
unzip("activity.zip", exdir=dataDir)
activity.df <- read.csv(paste0(dataDir, "/activity.csv"))
activty.head <- xtable(head(activity.df))
print(activty.head, type="html")
```


## What is mean total number of steps taken per day?

We remove rows without steps.
```{r total_steps_per_day, echo=TRUE}
require("data.table")
require("ggplot2")
activity.dt <- as.data.table(activity.df)
steps <- activity.dt[!is.na(steps),.(number=sum(steps)),by=date]

mean(steps$number)
steps.median <- median(steps$number)

steps.gg1 <- ggplot(steps, aes(x=number))
steps.gg1+geom_histogram(binwidth = 850) + geom_vline(xintercept = steps.median, colour = "red")
steps.gg2 <- ggplot(steps, aes(x=factor(0),y=number))
steps.gg2 + geom_boxplot()+coord_flip()
```


## What is the average daily activity pattern?


```{r}
steps2 <- activity.dt[,.(average=mean(steps, na.rm=TRUE),median=median(steps, na.rm=TRUE)),by=interval]


interval.max <- steps2[which.max(steps2[,average]),interval]
average.max <- steps2[which.max(steps2[,average]),average]

ggplot(steps2, aes(x=interval, y=average))+geom_line()+
    geom_vline(xintercept=interval.max, colour="red")+
        geom_hline(yintercept=average.max, colour="red")
#geom_line(aes(x=interval, y=median), colour="blue")

ggplot(steps2, aes(x=interval, y=median))+geom_line()


```
## Imputing missing values

```{r}
sum(activity.dt[,is.na(steps)])
sum(activity.dt[,is.na(interval)])
sum(activity.dt[,is.na(date)])
```

In order to clone we wrap by data.table

```{r}
activity.nona <- data.table(activity.dt)

steps.average <- function(int) {
  steps2[interval == int,average]
}

activity.nona[,steps := ifelse(is.na(steps), steps.average(interval), steps)]
steps.total.per.day <- activity.dt[,.(total=sum(steps, na.rm=TRUE)), by=date]
steps.total.per.day.nona <- activity.nona[,.(total=sum(steps)), by=date]
ggplot(steps.total.per.day)+geom_histogram(aes(x=total),binwidth=1000)
#qplot(total, data=steps.total.per.day, binwidth=1000)
ggplot(steps.total.per.day)+
    geom_line(aes(as.Date(date),steps.total.per.day.nona$total), color="blue")+
        geom_line(aes(as.Date(date), total), color="red")

steps.average.per.day <- activity.nona[,.(average=mean(steps)), by=date]
steps.median.per.day <- activity.nona[,.(median=median(steps)), by=date]



```

## Are there differences in activity patterns between weekdays and weekends?

```{r}
activity.nona[,day:=as.factor(
                   ifelse(
                       (weekdays(as.Date(date)) %in% c("Saturday","Sunday")),
                       "weekend","weekday"))
              ]

steps3 <- activity.nona[,.(average=mean(steps, na.rm=TRUE)),
                        by=.(interval, day)]
ggplot(steps3, aes(x=interval, y = average)) + geom_line()+facet_grid(day ~ .)
```
